[test]
greeting = "hi"
amount = -4.0
address = 0xDEADBEEF
ip = "192.168.1.1"
ports = [80, 443]
expose = true
contact = {
  cat = "meow",
  "bitch" = { qzip = true }
}
pawjob.sticky.value = 5.55

[test]
  a =" yep"
  dfd = -inf
  ffff = nan

["cool"]
  hi = """
      bro
  """

[["cool".stuff]]
  name = "HI"

[["cool".stuff]]
  name = "very cool item"

[["cool".stuff.yep]]
  agree = "indeed"
[["cool".stuff.stuffed]]
  stuffing = 100


[["cool".stuff]]
  name = "paws"

[["cool".stuff.another]]
  another-paw = true
  another.paw = "yes"

#[["cool".stuff]]
#  name = "pawws"
  
#[ j . "ʞ" . 'l' ] 
#a = "b"